//
//  Data.swift
//  EmiApp
//
//  Created by Sebastian Strus on 2019-04-07.
//  Copyright © 2019 Sebastian Strus. All rights reserved.
//

import Foundation


class Data {
    
    class func getWeatherWords() -> [Question] {
        return [Question(swedish: "Hur är vädret?", english: "How is the weather?"),
                Question(swedish: "Det är varmt", english: "It is hot"),
                Question(swedish: "Det är kallt", english: "It is cold"),
                Question(swedish: "Det är soligt", english: "It is sunny"),
                Question(swedish: "Den är molnigt", english: "It is cloudy"),
                Question(swedish: "Det är fuktigt", english: "It is humid"),
                Question(swedish: "Det regnar", english: "It is raining"),
                Question(swedish: "Det snöar", english: "It is snowing"),
                Question(swedish: "Det är blåsigt", english: "It is windy"),
                Question(swedish: "Det är otäckt", english: "It is nasty"),
                Question(swedish: "Vilken temperatur är det?", english: "What is the temperature?"),
                Question(swedish: "Det är 24 grader", english: "It is 24 degrees"),
                Question(swedish: "säsong", english: "season"),
                Question(swedish: "vinter", english: "winter"),
                Question(swedish: "sommar", english: "summer"),
                Question(swedish: "vår", english: "spring"),
                Question(swedish: "höst", english: "autumn"),
                Question(swedish: "alltid", english: "always"),
                Question(swedish: "aldrig", english: "never"),
                Question(swedish: "ofta", english: "often"),
                Question(swedish: "sällan", english: "seldom"),
                Question(swedish: "ibland", english: "sometimes"),
                Question(swedish: "vanligtvis", english: "usually"),
        ]
    }
    
    class func getVerbs() -> [Question] {
        return [Question(swedish: "stiga upp", english: "arise"),
                Question(swedish: "vakna", english: "awake"),
                Question(swedish: "vara", english: "be"),
                Question(swedish: "slå", english: "beat"),
                Question(swedish: "bli", english: "become"),
                Question(swedish: "börja", english: "begin"),
                Question(swedish: "böja", english: "bend"),
                Question(swedish: "slå vad", english: "bet"),
                Question(swedish: "bita", english: "bite"),
                Question(swedish: "blöda", english: "bleed"),
                Question(swedish: "blåsa", english: "blow"),
                Question(swedish: "bryta", english: "break"),
                Question(swedish: "föra", english: "bring"),
                Question(swedish: "bygga", english: "build"),
                Question(swedish: "brinna", english: "burn"),
                Question(swedish: "brista", english: "burst"),
                Question(swedish: "köpa", english: "buy"),
                Question(swedish: "fånga", english: "catch"),
                Question(swedish: "välja", english: "choose"),
                Question(swedish: "komma", english: "come"),
                Question(swedish: "kosta", english: "cost"),
                Question(swedish: "krypa", english: "kreep"),
                Question(swedish: "skära", english: "cut"),
                Question(swedish: "handla", english: "deal"),
                Question(swedish: "gräva", english: "dig"),
                Question(swedish: "göra", english: "do"),
                Question(swedish: "dra", english: "draw"),
                Question(swedish: "drömma", english: "dream"),
                Question(swedish: "dricka", english: "drink"),
                Question(swedish: "öra", english: "drive"),
                Question(swedish: "äta", english: "eat"),
                Question(swedish: "falla", english: "fall"),
                Question(swedish: "mata", english: "feed"),
                Question(swedish: "känna", english: "feel"),
                Question(swedish: "slåss", english: "fight"),
                Question(swedish: "hitta", english: "find"),
                Question(swedish: "fly", english: "flee"),
                Question(swedish: "slänga", english: "fling"),
                Question(swedish: "flyga", english: "fly"),
                Question(swedish: "förbjuda", english: "forbid"),
                Question(swedish: "glömma", english: "forget"),
                Question(swedish: "förlåten", english: "forgive"),
                Question(swedish: "frysa", english: "freeze"),
                Question(swedish: "få", english: "get"),
                Question(swedish: "ge", english: "give"),
                Question(swedish: "gå", english: "go"),
                Question(swedish: "växa", english: "grow"),
                Question(swedish: "hänga", english: "hang"),
                Question(swedish: "ha", english: "have"),
                Question(swedish: "höra", english: "hear"),
                Question(swedish: "gömma", english: "hide"),
                Question(swedish: "träffa", english: "hit"),
                Question(swedish: "hålla", english: "hold"),
                Question(swedish: "skada", english: "hurt"),
                Question(swedish: "behålla", english: "keep"),
                Question(swedish: "veta", english: "know"),
                Question(swedish: "lägga", english: "lay"),
                Question(swedish: "leda", english: "lead"),
                Question(swedish: "luta", english: "lean"),
                Question(swedish: "lära", english: "learn"),
                Question(swedish: "lämna", english: "leave"),
                Question(swedish: "låna", english: "lend"),
                Question(swedish: "låta", english: "let"),
                Question(swedish: "ligga", english: "lie"),
                Question(swedish: "tända", english: "light"),
                Question(swedish: "förlora", english: "lose"),
                Question(swedish: "göra", english: "make"),
                Question(swedish: "betyda", english: "mean"),
                Question(swedish: "möta", english: "meet"),
                Question(swedish: "betala", english: "pay"),
                Question(swedish: "ställa", english: "put"),
                Question(swedish: "sluta", english: "quit"),
                Question(swedish: "läsa", english: "read"),
                Question(swedish: "rida", english: "ride"),
                Question(swedish: "ringa", english: "ring"),
                Question(swedish: "stiga", english: "rise"),
                Question(swedish: "springa", english: "run"),
                Question(swedish: "säga", english: "say"),
                Question(swedish: "se", english: "see"),
                Question(swedish: "söka", english: "seek"),
                Question(swedish: "sälja", english: "sell"),
                Question(swedish: "skicka", english: "send"),
                Question(swedish: "sätta", english: "set"),
                Question(swedish: "skaka", english: "shake"),
                Question(swedish: "skina", english: "shine"),
                Question(swedish: "skjuta", english: "shoot"),
                Question(swedish: "visa", english: "show"),
                Question(swedish: "krympa", english: "shrink"),
                Question(swedish: "stänga", english: "shut"),
                Question(swedish: "sjunka", english: "sink"),
                Question(swedish: "sitta", english: "sit"),
                Question(swedish: "sova", english: "sleep"),
                Question(swedish: "glida", english: "slide"),
                Question(swedish: "lukta", english: "smell"),
                Question(swedish: "tala", english: "speak"),
                Question(swedish: "stava", english: "spell"),
                Question(swedish: "tillbringa", english: "spend"),
                Question(swedish: "spotta", english: "spit"),
                Question(swedish: "sprida", english: "spread"),
                Question(swedish: "stå", english: "stand"),
                Question(swedish: "stjäla", english: "steal"),
                Question(swedish: "sticka", english: "stick"),
                Question(swedish: "stinga", english: "sting"),
                Question(swedish: "stinka", english: "stink"),
                Question(swedish: "slå", english: "strike"),
                Question(swedish: "svära", english: "swear"),
                Question(swedish: "svepa", english: "sweep"),
                Question(swedish: "simma", english: "swim"),
                Question(swedish: "svänga", english: "swing"),
                Question(swedish: "ta", english: "take"),
                Question(swedish: "lära", english: "teach"),
                Question(swedish: "riva", english: "tear"),
                Question(swedish: "berätta", english: "tell"),
                Question(swedish: "tänka", english: "think"),
                Question(swedish: "kasta", english: "throw"),
                Question(swedish: "trampa", english: "tread"),
                Question(swedish: "förstå", english: "understand"),
                Question(swedish: "väcka", english: "wake"),
                Question(swedish: "bära", english: "wear"),
                Question(swedish: "väva", english: "weave"),
                Question(swedish: "gråta", english: "weep"),
                Question(swedish: "vinna", english: "win"),
                Question(swedish: "vrida", english: "wring"),
                Question(swedish: "skriva", english: "write")]
    }
    
    class func getUsefulWords() -> [Question] {
        return [Question(swedish: "Hur är vädret?", english: "How is the weather?"),
                Question(swedish: "Det är varmt", english: "It is hot"),
                Question(swedish: "Det är kallt", english: "It is cold"),
                Question(swedish: "Det är soligt", english: "It is sunny"),
                Question(swedish: "Den är molnigt", english: "It is cloudy"),
                Question(swedish: "Det är fuktigt", english: "It is humid"),
                Question(swedish: "Det regnar", english: "It is raining"),
                Question(swedish: "Det snöar", english: "It is snowing"),
                Question(swedish: "Det är blåsigt", english: "It is windy"),
                Question(swedish: "Det är otäckt", english: "It is nasty"),
                Question(swedish: "Vilken temperatur är det?", english: "What is the temperature?"),
                Question(swedish: "Det är 24 grader", english: "It is 24 degrees"),
                Question(swedish: "säsong", english: "season"),
                Question(swedish: "vinter", english: "winter"),
                Question(swedish: "sommar", english: "summer"),
                Question(swedish: "vår", english: "spring"),
                Question(swedish: "höst", english: "autumn"),
                Question(swedish: "alltid", english: "always"),
                Question(swedish: "aldrig", english: "never"),
                Question(swedish: "ofta", english: "often"),
                Question(swedish: "sällan", english: "seldom"),
                Question(swedish: "ibland", english: "sometimes"),
                Question(swedish: "vanligtvis", english: "usually"),
        ]
    }
}




